### PR TITLE
change sample level to make the handles line up with the default grid

### PR DESCRIPTION
**Pull request by nobody5050**

### CODE REVIEW

**Comment by getkey** [comment]
Does it still make a cubehat? 😄

**Comment by nobody5050** [comment]
Good question xD

**Comment by nobody5050** [comment]
aaand, nope

**Comment by getkey** [comment]
Yeah Sky4ce09 made it that way so it would create a cubehat.
But it would be cool to have your cake and eat it too.

**Comment by nobody5050** [comment]
After much work, it appears to be impossible. I’ll close this until I can figure out a way or most likely indefinitely in order to keep the cubehat.

**Pull request closed without merging**
