### PR TITLE
Made Cursors in src/icons white to improve visibility

### PR DESCRIPTION
**Pull request by v0Xal**
I had to clone it to my computer because github online doesn't let me delete multiplue files

### CODE REVIEW

**Comment by getkey** [comment]
Thanks for the PR! It's easier to see the cursor against the black background, however this also changes the color of the icons on the top-left corner. :stuck_out_tongue: 

image

To prevent this issue, usually cursors have a fill color different from their stroke color for example:

cursors

On my computer it's the opposite, I have the adawaita cursors [which are black with a white fill](http://www.rw-designer.com/cursor-set/adwaita).

Anyway, if you change the `stroke-width` and the `stroke` the cursors will be visible against any background color. :slightly_smiling_face:

**Comment by v0Xal** [comment]
Ok ill try that

**Comment by v0Xal** [comment]
image
thats a issue

**Comment by getkey** [comment]
If you have inkscape select both rectangle -> convert to path. And afterwards both will be merged into one object I think so the outline will look normal.

> you add black icons as well and then switch between them

True. But even so, it's nice to make an outline because the normal blocks are grey-white so while a white icon will be visible an outline will make it even more so.

**Comment by v0Xal** [comment]
Ok. I just updated the add_block svg.

**Comment by getkey** [comment]
image


You need to make the stroke-width bigger because, the image is downsized.

By the way, once you're all done, could you optimize the SVGs with [svgo](https://jakearchibald.github.io/svgomg/) :pray:

**Comment by v0Xal** [comment]
Ok its almost done. Im going to svgo to shrink

**Comment by v0Xal** [comment]
Ok it should be done now!

**Pull request merged**
