### PR TITLE
updated normal polygon and circle colour

### LINKED ISSUE #78: Use the same colors for the block as in game
https://discord.com/channels/526188679006388254/707318664201896007/979445035311431720

### PR DESCRIPTION
**Pull request by enjiruuuu**
Closes #78

### CODE REVIEW

**Comment by enjiruuuu** [comment]
i just realised this issue doesn't have the help wanted tag, can I still make this PR?

**Comment by getkey** [comment]
Of course!
But please use the same formula that's used in game, which I digged up below:

```js
import { lab } from 'd3-color';
import { interpolateLab } from 'd3-interpolate';
import { utils } from 'pixi.js';

export const darkSlateGray = 0x121f1f;

lab(
	interpolateLab(
		utils.hex2string(color),
		utils.hex2string(darkSlateGray),
	)(0.7),
).formatHex()
```

Can you do it for all the blocks?

**Comment by enjiruuuu** [comment]
should i be using the exact same formula? from what i've seen, the color will turn out to be way darker than expected. for example, this:

Screenshot 2022-05-29 at 4 01 44 PM

versus this:

Screenshot 2022-05-29 at 4 04 01 PM

Otherwise, do you mean to use a similar method like this?

```typescript
utils.string2hex(
	lab(
		utils.hex2string(color)
	).formatHex(),
)
```

**Comment by getkey** [comment]
Oh yeah, that's because in game the inside of the block is very dark, and the line around isn't.

image

Here is the formula for the line.

```js
export function getLineColor(color) {
	return utils.string2hex(
		lab(utils.hex2string(color))
			.brighter(1.2)
			.formatHex(),
	);
}
```

You can try adding the line while keeping the dark fill.

If adding the line is too complicated, just play around with the `interpolateLab` parameter until you get something that looks decent, maybe with lower values like `0.1` or `0.2` instead of `0.7`.

**Comment by enjiruuuu** [comment]
gotcha, thanks! I've made the updates to the PR. 

Given that the same formula (originally ```getStrokeColor```) is used now across multiple places, I thought that ```getFillColor``` is a more accurate name for the method.

**Review by getkey — CHANGES_REQUESTED** [review]
image

Whoa looks very good! :smile:

I found a bug: if you click the bouncy block, the selection box doesn't appear.
[selection_bug_test_case.json.txt](https://github.com/getkey/ble/files/8809640/selection_bug_test_case.json.txt) (rename this file to JSON)

I tried playing around with `src/components/Polygon.ts` and `src/components/SelectionAabb.ts` to understand what's going on, but I found nothing particular 😕. It might be a bug in Pixi, so you can try making a minimal reproduction in [pixiplayground](https://pixiplayground.com/) (make sure to use the same version of Pixi).

**Comment by enjiruuuu** [comment]
thank you! 😄 I've updated just the syntax for now and will continue investigating the bug.


From what I've seen, it seems to be happening when I add the ```instance.lineStyle``` method in ```Polygon.ts``` . It's strange because it seems to only be happening for the second polygon added, regardless of type.

**Comment by enjiruuuu** [comment]
@getkey what are the steps you took to trigger the bug?

I have tried clearing my level and adding 2 polygons, then exporting them and importing them back in but that works ok for me. I've only been able to replicate the issue by loading in the file you have provided but was wondering what steps were taken to create that particular file.

**Comment by getkey** [comment]
This is a Pixi.js bug, which I've reported upstream: https://github.com/pixijs/pixijs/issues/8409. Let's wait until it is resolved in Pixi.js.

**Comment by getkey** [comment]
@enjiruuuu I upgraded to the latest Pixi.js, and [surely enough the selection bug is gone](https://github.com/pixijs/pixijs/issues/8409#issuecomment-1159551106). :slightly_smiling_face: 

One remaining problem: the paints get block styles. [Example](https://bombhopper.io/?level=c0175d29-68ef-4648-a38f-d301695d30bd):
image

I'd make a new `BlockPolygon` component that would be used for all blocks, and keep the old `Polygon` to be used for paints. (In the future there could be even more specialized `Polygon`s like `IcePolygon` with the ice texture, but I think this is good enough for now :slightly_smiling_face: )

**Comment by enjiruuuu** [comment]
@getkey sweet, thanks for the update!

I've made the fix in the recent commit, do let me know if this is what you meant haha incase I misunderstood something 😬

**Comment by getkey** [comment]
Mhh I'm having second thoughts, because I realize now that `BlockPolygon` and `Polygon` are 90% copy-paste of each other.

You can make Polygon more generic. Make it purely about drawing, and move the logic of _what_ to draw higher in the hierarchy. Let it accept:
- the vertices
- the fill color
- the stroke color
- the stroke width (can be 0)
- the texture (can be null)
- etc

Then you can make 2 React components: `Paint.tsx` and `Block.tsx`. They both rely on `ModifiablePolygon`and know what are the right styles for a paint or a block. I prefer that compared to adding `addType` to `ModifiablePolygon`, because in my experience you don't want to cram conditional config in a single component, that will turn in technical debt.

Note: `ModifiablePolygon` [magically forwards](https://github.com/getkey/ble/pull/79/files#diff-a65ba4d389baa6cedae5165d931f7c4ec953c87b2799830a481aad36e96381e5L37) the props to `Polygon`, but let me know if the type-checker gives you trouble.

**Pull request closed without merging**
